// commands/affirmations.js
module.exports = [
  "You are allowed to take up space and exist exactly as you are.",
  "It’s okay to rest—your worth is not measured by productivity.",
  "You are doing your best, and that is more than enough.",
  "Your feelings matter, and you deserve to honor them.",
  "Growth is not linear; every step, even backwards, is part of your journey.",
  "You are worthy of kindness, including your own.",
  "Small steps count as progress; celebrate every little victory.",
  "You bring a light to the world that no one else can.",
  "It’s safe to let go of what you can’t control.",
  "You have survived every difficult day so far. You’re stronger than you think.",
  "Your presence is a gift, even on the days you feel invisible.",
  "You are allowed to set boundaries and protect your peace.",
  "Your journey is your own; there is no deadline for healing or growth.",
  "It’s okay to ask for help—receiving support is a form of strength.",
  "You are more resilient than you give yourself credit for.",
  "You can begin again as many times as you need.",
  "You deserve rest, joy, and gentle moments.",
  "Your dreams and desires are valid and meaningful.",
  "Self-care is not selfish; it’s an act of love.",
  "You are enough, just by being you.",
  "You are worthy of love, respect, and acceptance.",
  "Mistakes are just stepping stones to learning and growth.",
  "You bring something special to every space you enter.",
  "Your needs and boundaries are important.",
  "It’s brave to keep going, even when it’s hard.",
  "You have permission to feel whatever you’re feeling.",
  "You can find peace in this moment, no matter what’s happening.",
  "You are learning and growing every single day.",
  "It’s okay to take things one step at a time.",
  "You are not defined by your struggles.",
  "You have a kind heart, and that matters.",
  "There is strength in being gentle with yourself.",
  "You are making progress, even if you can’t see it yet.",
  "You are not alone; support is available to you.",
  "You can turn a new page at any moment.",
  "Your voice and story matter.",
  "You are more than your doubts or fears.",
  "Caring for yourself is a worthy priority.",
  "You have gifts the world needs.",
  "Every part of you is worthy of compassion.",
];
